apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: css-site-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: css-site.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: css-site-service
            port:
              number: 80